apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: insert-field-action
  annotations:
    camel.apache.org/provider: "Red Hat"
    camel.apache.org/kamelet.group: "Actions"
  labels:
    camel.apache.org/kamelet.type: "action"
    camel.apache.org/kamelet.version: "0.0.1"
spec:
  definition:
    title: "Insert Field Action"
    description: "Adds a custom field with a constant value to the message in transit"
    required:
      - field
      - value
    properties:
      field:
        title: Field
        description: The name of the field to be added
        type: string
      value:
        title: Value
        description: The value of the field
        type: string
    type: object
  dependencies:
  - "github:apache.camel-kamelets:camel-kamelets-utils:main-SNAPSHOT"
  - "camel:core"
  - "camel:jackson"
  - "camel:kamelet"
  flow:
    from:
      uri: kamelet:source
      steps:
      - choice:
          when:
          - simple: "${header[Content-Type]} == 'application/json'"
            steps:
            - set-property:
                name: deserialized
                constant: "true"
            - unmarshal:
                json:
                  library: Jackson
                  unmarshalTypeName: com.fasterxml.jackson.databind.JsonNode
      - set-property:
          name: "field"
          constant: "{{field}}"
      - set-property:
          name: "value"
          constant: "{{value}}"
      - bean: "org.apache.camel.kamelets.utils.transform.InsertField"
      - choice:
          when:
          - simple: "${exchangeProperty[deserialized]} == 'true'"
            steps:
            - marshal:
                json:
                  library: Jackson
                  unmarshalTypeName: com.fasterxml.jackson.databind.JsonNode
            - set-header:
                name: "Content-Type"
                constant: "application/json"
