kind: Service
apiVersion: v1
metadata:
#  annotations:
#    prometheus.io/path: /q/metrics
#    prometheus.io/port: '8080'
#    prometheus.io/scheme: http
#    prometheus.io/scrape: 'true'
  name: cos-fleet-catalog-camel
  labels:
    app.kubernetes.io/name: cos-fleet-catalog-camel
    app.kubernetes.io/part-of: kas-fleet-manager
#    app.kubernetes.io/version: brain
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: cos-fleet-catalog-camel
    app.kubernetes.io/part-of: kas-fleet-manager
#    app.kubernetes.io/version: brain
  type: ClusterIP
