name: Deploy Images

on:
  push:
    branches:
      - main
    paths:
      - 'cos-fleet-catalog-connectors-images/pom.xml'
      - 'cos-fleet-catalog-connectors-images/**/**'
      - '.github/workflows/deploy-images.yaml'
  workflow_dispatch:

env:
  LANG: en_US.UTF-8
  MAVEN_OPTS: -Xmx3000m
  MAVEN_ARGS: -V -ntp -Dhttp.keepAlive=false -e

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: openshift/origin-cli:latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build Project
        run: |
          ./mvnw ${MAVEN_ARGS} clean install
      - name: Deploy Images
        env:
            IMAGE_REPO_USERNAME: ${{secrets.QUAY_MCI_USR}}
            IMAGE_REPO_PASSWORD: ${{secrets.QUAY_MCI_PWD}}
        run: |
          for D in cos-fleet-catalog-connectors-images/*; do
            NAME=$(basename "${D}")

            if [[ -d "${D}" ]]
            then
              ./mvnw ${MAVEN_ARGS} clean package \
                -Dquarkus.container-image.username="${IMAGE_REPO_USERNAME}" \
                -Dquarkus.container-image.password="${IMAGE_REPO_PASSWORD}" \
                -Dquarkus.container-image.registry=quay.io \
                -Dquarkus.container-image.group=lburgazzoli \
                -Pcontainer-push \
                -pl :"${NAME}"
          done
