name: Deploy Catalog

on:
  push:
    branches: 
      - main
    paths:
      - 'etc/connectors/**/*.json'
      - 'etc/scripts/*.sh'
      - '.github/workflows/deploy.yaml'
  workflow_dispatch:

env:
  LANG: en_US.UTF-8

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: openshift/origin-cli:latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Install OpenShift CLI tools
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: "mirror"
          skip_cache: "true"
          oc: "latest"
      - name: Verify OpenShift CLI tools
        run: |
          oc version
      - name: Log in and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.K8S_CLUSTER_DEV }}
          openshift_username: ${{ secrets.K8S_CLUSTER_DEV_USER }}
          openshift_password: ${{ secrets.K8S_CLUSTER_DEV_PASSWORD }}
          insecure_skip_tls_verify: true
          namespace: ${{ env.K8S_CLUSTER_DEV_NAMESPACE }}
      - name: Deploy Catalog
        run: |
          ./etc/scripts/deploy.sh  ${{ secrets.K8S_CLUSTER_DEV_NAMESPACE }}