name: Deploy Catalog

on:
  push:
    branches: 
      - main
    paths:
      - 'etc/connectors/**/*.json'
      - 'etc/scripts/*.sh'
      - '.github/workflows/deploy.yaml'
  workflow_dispatch:

env:
  LANG: en_US.UTF-8

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: openshift/origin-cli:latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Login to OpenShift cluster
        run: |
          oc login \
            --insecure-skip-tls-verify ${{ secrets.K8S_CLUSTER_DEV }} \
            -u ${{ secrets.K8S_CLUSTER_DEV_USER }} \
            -p ${{ secrets.K8S_CLUSTER_DEV_PASSWORD }}
      - name: Deploy Catalog
        run: |
          ./etc/scripts/deploy.sh  ${{ secrets.K8S_CLUSTER_DEV_NAMESPACE }}